# Bayesian Linear Regression  

-----------

_Author: Khal Makhoul, W.P.G.Peterson_  

## Project Guide

--------------

- [Project Overview](#overview)
- [Introduction and Review](#intro)
- [Coding Bayesian Linear Regression](#code)
- [Data Refresher](#data)

<a id = "overview"></a>
## Project Overview  

------------
#### EXPECTED TIME 3 HRS

This assignment will test your abilities in two different sections: the [review](#intro) section will revisit Bayes' formula and evaluate your ability to calculate simple Bayesian posterior probabilities. The [coding](#code) section will ask you to build functions that calculate the parameters of Bayesian posteriors for Bayesian Linear Regression.  

In a separate notebook, there is a brief demonstration of `pymc3`. The `pymc3` module is a standard for using Markov Chain Monte Carlo to estimate Bayesian derived distributions, in lieu of calculating exact integrals.  
One note on `pymc3`: it may be tricky to make function on your individual machine

Programming questions will include:
- Calculation of Bayesian Posterior
- Calculating the $w_{MAP}$
- Estimating $\sigma^2$
- Calculating $\Sigma$  

**Motivation**: Bayesian regression allows us to quantify the uncertainty in our model building / the point estimates of our weights calculated in Least Squares Regression.  

**Objectives**: This assignment will:
- Test fundamental Bayesian knowledge, particulary in regard to Linear Regression
- Introduce `pymc3`  

**Problem**: Once again we will be using housing data to predict house price using living area and year built.  

**Data**: Our data comes from [Kaggle's House Prices Dataset](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data). 

#### Imports:


In [191]:
### This cell imports the necessary modules and sets a few plotting parameters for display

%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (20.0, 10.0)  


<a id = "intro"></a>
### Introduction and Review.

Bayesian Regression comes with a different toolset than ordinary Linear Regression. In turn, that toolset demands a slightly different mindset. We start with a short review to hightlight the ways in which Bayesian thinking proceeds.

Consider a population whose age distribution is as follows:

| Age group | $\%$ of total population   |
|------|------|
|   $\le 35$  | $25 \%$|
| $36-65$ | $45 \%$ |
| $\ge 66$ | $30 \%$|

Say you know the following results of a study about YouTube viewing habits:

| Age group | $\%$ in this group that watch YouTube every day  |
|------|------|
|   $\le 35$  | $90 \%$|
| $36-65$ | $50 \%$  |
| $\ge 66$ | $10 \%$ |

**Prompt: If you know a user watches YouTube every day, what is the probability that they are under 35?**


We will start with a prior, then update that prior using the likelihood and the normalization from Bayes's formula. We define the following notation:

* $A$: YouTube watching habit
* $B$: Age
* $A = 1$: User watches YouTube every day 
* $A = 0$: User does not watch YouTube every day
* $B \le 35$: User has age between 0 and 35
* $36 \le B \le 65$: User has age between 36 and 65
* $B \ge  66$: User has age greater than 65

The prior can be read from the first table: 

$$P(B \le 35) = 0.25$$

We are looking to calculate the posterior probability:

$$P(B \le 35|A = 1)$$

With Bayes's formula:

$$P(B|A) = \frac{P(A|B)P(B)}{P(A)}$$

For our question:

$$P(B \le 35|A=1) = \frac{P(A=1|B \le 35)*P(B \le 35)}{P(A=1)}$$  

While the tables do not contain the value of $P(A=1)$ it may be calculated:  

$P(A=1) = $  


$\ \ \ \ \ \ \ \ \ \ \ \ P(A=1| B\le 35)*P(B\le 35) \ + $  

$\ \ \ \ \ \ \ \ \ \ \ \ P(A=1|35<B<65)* P(35<B<65)\  + $  

$\ \ \ \ \ \ \ \ \ \ \ \ P(A=1|B\ge 65)*P(B\ge 65)$

#### Question 1

In [ ]:
### GRADED
### In the example above, P(A=1|B<35) is the:
### 'a')prior
### 'b')liklihood
### 'c')nomalization
### 'd')posterior

### assign character associated with your choice as string to ans1
### YOUR ANSWER BELOW

ans1 = 'c'

In [ ]:
#
# AUTOGRADER TEST - DO NOT REMOVE
#


#### Question 2

In [ ]:
### GRADED
### Given the values in the tables above, calculate the posterior for:

### "If you know a user watches Youtube every day,
### what is the probability that they are under 35?"

### Assign float (posterior probability between 0 and 1) to ans1

### YOUR ANSWER BELOW

ans1 = 0.46875000000000006

In [3]:
    # Given A what is Prob(B) => Pr(B | A )
    # Pr(B | A) = {Pr ( A |B ) * Pr(B)} / Pr(A) 
    x = .9*.25 + (.5*.45) + (.1*.3)
    y = .9*.25
    ans = y/x
    ans

0.46875000000000006

In [ ]:
#
# AUTOGRADER TEST - DO NOT REMOVE
#


#### Question 3

In [68]:
### GRADED
### Code a function called `calc_posterior`

### ACCEPT three inputs
### Two floats: the likelihood and the prior
### One list of tuples, where each tuple has two values corresponding to:
### ### ( P(Bn) , P(A|Bn) )
### ### ### Assume the list of tuples accounts for all potential values of B
### ### ### And that those values of B are all mutually exclusive.
### The list of tuples allows for the calculation of normalization constant.

### RETURN a float corresponding to the posterior probability

### YOUR ANSWER BELOW

def calc_posterior(likelihood, prior, norm_list):
    lng = len(norm_list)
    count = 0
    my_denom = []
    
    while (count < lng):
        for x in norm_list:
            x = norm_list[count][0]
            y = norm_list[count][1]
            denom = x*y
            my_denom.append(denom)
            count=count+1
    top = likelihood*prior
    bottom = sum(my_denom)
    result = top/bottom
    return result 
    """
    Calculate the posterior probability given likelihood,
    prior, and normalization
    
    Positional Arguments:
        likelihood -- float, between 0 and 1
        prior -- float, between 0 and 1
        norm_list -- list of tuples, each tuple has two values
            the first value corresponding to the probability of a value of "b"
            the second value corresponding to the probability of 
                a value of "a" given that value of "b"
    Example:
        likelihood = .8
        prior = .3
        norm_list = [(.25 , .9), (.5, .5), (.25,.2)]
        print(calc_posterior(likelihood, prior, norm_list))
        # --> 0.45714285714285713
    """

In [69]:
    # TESTING FOR ABOVE FUNCTION 
    likelihood = .8
    prior = .3
    norm_list = [(.25 , .9), (.5, .5), (.25,.2)]
    print(calc_posterior(likelihood, prior, norm_list))

0.45714285714285713


In [ ]:
#
# AUTOGRADER TEST - DO NOT REMOVE
#


#### Applicability

In real life, this situation corresponds to:  
1. Surveying people and asking them two questions (what's your age? do you watch YouTube every day?), then tabulating the percentage of each age group that watch YouTube everyday.
2. After having collected that data, observing the anonymized watching habits of a set of different users (not the survey takers) - without access to additional demographic info -  and using the above survey to derive a probability for the anonymized users' age.

### Bayesian Linear Regression

In Bayesian Linear Regression, our prior expresses a belief about the parameters of linear regression we wish to calculate, namely that the linear coefficient vector should have a small absolute value, and that deviations from zero should be Gaussian. This prior is mathematically equivalent to the Ridge Regression condition.

So the question we will now ask is: conditioned on the data, how does our belief regarding the parameters of linear regression change? 

This is the same prior-to-posterior calculation of the above exercise.  

Bayes' Rule:

$P(B|A) = \frac{P(A|B)\ P(B)}{P(A)}$,

For linear Regression:

$p(w | y, X) = \frac{p(y | w, X)\ p(w)}{p(y | X)}$  

What do we know, and what do we not know?

* $p(w) = N(0, \lambda^{-1} I)$: That's the prior on $w$ --- Known.  


* $p(y | w, X) = N(X w, \sigma^2 I)$: That's the likelihood expression --- Known.  


* $p(y | X)$: That's the marginal probability of $y$ --- NOT KNOWN

Rewriting the marginal probability in detail, using an integral instead of a sum - since $w$ is a continuous variable.

$p(y | X) = \int_{\mathbb{R^d}} p(y, w | X)\ dw$

$\ \ \ \ \ \ \ \ \ \ = \int_{\mathbb{R^d}}\ p(y | w, X)\  p(w)\ dw$


At this point approximation is frequently required as the above integral usually has no closed form.  

<a id= "code"></a>

### Coding Bayesian Linear Regression

In lecture, we obtained an equation for the posterior probability of $w$, the linear regression parameter vector:

$$p(w|y, X) = N(w|\mu, \Sigma)$$

#### where

$$\Sigma = (\lambda \ I + \sigma^{- 2}\ X^T\ X)^{−1}$$

$$\mu = (\lambda \ \sigma^2 I + X^T\ X)^{-1}\ X^T y ⇐ w_{MAP}$$



Recall that $\sigma^2$ is a parameter characterizing the deviation of the data from the line defined by $Xw$. While we don't know the true underlying parameter, we can estimate it by using the empirical deviation:

$$\sigma^2 \approx \hat{\sigma}^2 = \frac{1}{n − d}\Sigma_{i=1}^n ( y_i − X_i w )^2$$  
Where $w$ in the above is the $w_{LeastSquares} = (X^T\ X)^{-1}\ X^T y$


-----------------------
When it comes to prediction:  
$p( y_0|x_0,y,X) = N(y_0|\mu_0,\sigma^2_0)$  
$\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \mu_0 = x^T_0\mu$  
$\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \sigma^2_0 = \sigma^2 + x_0^T\Sigma x_0$  

-----------------------------
This section will involve coding five functions:
- `x_preprocess`
- `calculate_map_coefficients`
- `estimate_data_noise`
- `calc_post_cov_mtx`
- `predict` 

Such that the functions `fit_bayes_reg` and `predict_bayes_reg` - outlined below - will work correctly. 

In [ ]:
def fit_bayes_reg(input_x, output_y, lambda_param):
    
    # Ensure correct shape of X, add column of 1's for intercept
    aug_x = x_preprocess(input_x) # <----
    
    # Calculate least-squares weights
    ml_weights = calculate_map_coefficients(aug_x, output_y, 0, 0) # <----
        
    # Estimate sigma^2 from observations
    sigma_squared = estimate_data_noise(aug_x, output_y, ml_weights) # <----
    
    # Calculate MAP weights
    weights = calculate_map_coefficients(aug_x, output_y, lambda_param, sigma_squared) # <---- 

    
    # Create posterior covariance matrix
    big_sig = calc_post_cov_mtx(aug_x, sigma_squared, lambda_param) # <----
    
    return weights, big_sig

def predict_bayes_reg(x_obs, weights, big_sig):
    
    # Ensure correct shape of X, add 1's for intercept
    aug_x = x_preprocess(x_obs) # <----
    
    # find mean / variance parameters describing prediction for data
    mu_0, sig_sq_0 = predict(aug_x, weights, big_sig) # <----
    
    return mu_0, sig_sq_0

#### Question 4: X-matrix preprocessing

In [158]:
### GRADED
### Build a function called "x_preprocess"
### ACCEPT one input, a numpy array
### ### Array may be one or two dimensions

### If input is two dimensional, make sure there are more rows than columns
### ### Then prepend a column of ones for intercept term
### If input is one-dimensional, prepend a one

### RETURN a numpy array, prepared as described above,
### which is now ready for matrix multiplication with regression weights

def x_preprocess(input_x):
    if (input_x.ndim > 1):
        if( input_x.shape[0] < input_x.shape[1]):
            input_x = np.transpose(input_x)
        prepend = np.ones(len(input_x)).reshape(len(input_x),1)
        input_x = np.concatenate((prepend, input_x), axis = 1) 
    elif (input_x.ndim == 1):
        input_x = np.insert(input_x,0,1)
    """
    Reshape the input (if needed), and prepend a "1" to every observation
    
    Positional Argument:
        input_x -- a numpy array, one- or two-dimensional
    
    Example:
        input1 = np.array([[2,3,6,9],[4,5,7,10]])
        input2 = np.array([2,3,6])
        input3 = np.array([[2,4],[3,5],[6,7],[9,10]])
        
        for i in [input1, input2, input3]:
            print(x_preprocess(i), "\n")
            
        # -->[[ 1.  2.  4.]
              [ 1.  3.  5.]
              [ 1.  6.  7.]
              [ 1.  9. 10.]] 

            [1 2 3 6] 

            [[ 1.  2.  4.]
             [ 1.  3.  5.]
             [ 1.  6.  7.]
             [ 1.  9. 10.]] 

    Assumptions:
        Assume that if the input is two dimensional, that the observations are more numerous
        than the features, and thus, the observations should be the rows, and features then columns
    """
    return input_x

In [157]:
            # *** TESTING FOR ABOVE FUNCTION *** # 
    #input_x = np.array([[2,3,6,9],[4,5,7,10]]) # TEST CASE 1: Cleared 
    #input_x = np.array([2,3,6]) # TEST CASE 2: cleared 
    #input_x = np.array([[2,4],[3,5],[6,7],[9,10]]) # TEST CASE 3 : Cleared
        
    if (input_x.ndim > 1):
        if( input_x.shape[0] < input_x.shape[1]):
            input_x = np.transpose(input_x)
        prepend = np.ones(len(input_x)).reshape(len(input_x),1)
        input_x = np.concatenate((prepend, input_x), axis = 1) 
    elif (input_x.ndim == 1):
        input_x = np.insert(input_x,0,1)
        
    
    input_x

array([[ 1.,  2.,  4.],
       [ 1.,  3.,  5.],
       [ 1.,  6.,  7.],
       [ 1.,  9., 10.]])

In [ ]:
#
# AUTOGRADER TEST - DO NOT REMOVE
#



#### Question 5: MAP Coefficients:

$$\mu = (\lambda \ \sigma^2 I + X^T\ X)^{-1}\ X^T y = w_{MAP}$$ 

In [232]:
### GRADED
### Build a function called `calculate_map_coefficients`

### ACCEPT four inputs:
### Two numpy arrays; an X-matrix and y-vector
### Two positive numbers, a lambda parameter, and value for sigma^2

### RETURN a 1-d numpy vector of weights.

### ASSUME your x-matrix has been preprocessed:
### observations are in rows, features in columns, and a column of 1's prepended.

### Use the above equation to calculate the MAP weights.
### ### This will involve creating the lambda matrix.
### ### The MAP weights are equal to the Ridge Regression weights

### NB: `.shape`, `np.matmul`, `np.linalg.inv`,
### `np.ones`, `np.identity` and `np.transpose` will be valuable.

### If either the "sigma_squared" or "lambda_param" are equal to 0, the return will be
### equivalent to ordinary least squares.

### YOUR ANSWER BELOW

def calculate_map_coefficients(aug_x, output_y, lambda_param, sigma_squared):
    lamb = np.identity(len(aug_x[0])) 
    # lambda*sigma_squared*I_matrix 
    first_var = (lambda_param*sigma_squared)*lamb
    # xMatrix * xMatrix.T 
    second_var = aug_x.T@aug_x
    # lambda*sigma_squared*I_matrix + xMatrix.T * xMatrix 
    part1 = np.linalg.inv(np.add(first_var,second_var))
    # xMatrix.T*yVector 
    part2 = aug_x.T@output_y
    coefs = part1@part2
    if ((lambda_param == 0) or (sigma_squared == 0)):
        coefs = np.linalg.inv(second_var)@part2
    return coefs
    
    
    """
    Calculate the maximum a posteriori LR parameters
    
     Positional arguments:
        aug_x -- x-matrix of training input data, augmented with column of 1's
        output_y -- vector of training output values
        lambda_param -- positive number; lambda parameter that
            controls how heavily to penalize large coefficient values
        sigma_squared -- data noise estimate
        
    Example:
        output_y = np.array([208500, 181500, 223500, 
                             140000, 250000, 143000, 
                             307000, 200000, 129900, 
                             118000])
                             
        aug_x = np. array([[   1., 1710., 2003.],
                           [   1., 1262., 1976.],
                           [   1., 1786., 2001.],
                           [   1., 1717., 1915.],
                           [   1., 2198., 2000.],
                           [   1., 1362., 1993.],
                           [   1., 1694., 2004.],
                           [   1., 2090., 1973.],
                           [   1., 1774., 1931.],
                           [   1., 1077., 1939.]])
                           
        lambda_param = 0.01
        
        sigma_squared = 1000
        
        map_coef = calculate_map_coefficients(aug_x, output_y, 
                                             lambda_param, sigma_squared)
                                             
        ml_coef = calculate_map_coefficients(aug_x, output_y, 0,0)
        
        print(map_coef)
        # --> np.array([-576.67947107   77.45913349   31.50189177])
        
        print(ml_coef)
        #--> np.array([-2.29223802e+06  5.92536529e+01  1.20780450e+03])
        
    Assumptions:
        -- output_y is a vector whose length is the same as the
        number of rows in input_x
        -- input_x has more observations than it does features.
        -- lambda_param has a value greater than 0
    """
    

In [234]:
           ### TESTING 
    
        output_y = np.array([208500, 181500, 223500, 
                             140000, 250000, 143000, 
                             307000, 200000, 129900, 
                             118000])
                             
        aug_x = np. array([[   1., 1710., 2003.],
                           [   1., 1262., 1976.],
                           [   1., 1786., 2001.],
                           [   1., 1717., 1915.],
                           [   1., 2198., 2000.],
                           [   1., 1362., 1993.],
                           [   1., 1694., 2004.],
                           [   1., 2090., 1973.],
                           [   1., 1774., 1931.],
                           [   1., 1077., 1939.]])
        lambda_param = 0.01
        sigma_squared = 1000
        
        # Lambda matrix     
        lamb = np.identity(len(aug_x[0])) 
        # lambda*sigma_squared*I_matrix 
        first_var = (lambda_param*sigma_squared)*lamb
        # xMatrix * xMatrix.T 
        second_var = aug_x.T@aug_x
        # lambda*sigma_squared*I_matrix + xMatrix.T * xMatrix 
        part1 = np.linalg.inv(np.add(first_var,second_var))
        # xMatrix.T*yVector 
        part2 = aug_x.T@output_y
        coefs = part1@part2

        ml_coef = calculate_map_coefficients(aug_x, output_y, 0,0)
        ml_coef
        

array([-2.29223802e+06,  5.92536529e+01,  1.20780450e+03])

#### Question 6: Estimate Data Noise
$$\sigma^2 \approx \hat{\sigma}^2 = \frac{1}{n − d}\Sigma_{i=1}^n ( y_i − X_i w )^2$$  

In [238]:
### GRADED
### Code a function called `esimate_data_noise`

### ACCEPT three inputs, all numpy arrays
### One matrix coresponding to the augmented x-matrix
### Two vectors, one of the y-target, and one of ML weights.

### RETURN the empirical data noise estimate: sigma^2. Calculated with equation given above.

### NB: "n" is the number of observations in X (rows)
### "d" is the number of features in aug_x (columns) 

### YOUR ANSWER BELOW

def estimate_data_noise(aug_x, output_y, weights):
    n = aug_x.shape[0]
    d = aug_x.shape[1]
    # empty list 
    sqdiflist = []
    # Xi*weights
    xiweights = -1*aug_x@weights
    # output_y - Xi*weights
    diff = np.add(output_y,xiweights)
    sqdiff = np.square(diff)
    # Appending empty list 
    for x in sqdiff:
        sqdiflist.append(x)
    # Summing the terms 
    squares_summed = sum(sqdiflist)
    # Finding sigma^2
    noise = (1/(n-d))*squares_summed
    return noise
    
        
    """Return empirical data noise estimate \sigma^2
    Use the LR weights in the equation supplied above
    
    Positional arguments:
        aug_x -- matrix of training input data
        output_y -- vector of training output values
        weights -- vector of LR weights calculated from output_y and aug_x
        
        
    Example:
        output_y = np.array([208500, 181500, 223500, 
                                140000, 250000, 143000, 
                                307000, 200000, 129900, 
                                118000])
        aug_x = np. array([[   1., 1710., 2003.],
                           [   1., 1262., 1976.],
                           [   1., 1786., 2001.],
                           [   1., 1717., 1915.],
                           [   1., 2198., 2000.],
                           [   1., 1362., 1993.],
                           [   1., 1694., 2004.],
                           [   1., 2090., 1973.],
                           [   1., 1774., 1931.],
                           [   1., 1077., 1939.]])
        
        ml_weights = calculate_map_coefficients(aug_x, output_y, 0, 0)
        
        print(ml_weights)
        # --> [-2.29223802e+06  5.92536529e+01  1.20780450e+03]
        
        sig2 = estimate_data_noise(aug_x, output_y, ml_weights)
        print(sig2)
        #--> 1471223687.1593
        
    Assumptions:
        -- training_input_y is a vector whose length is the same as the
        number of rows in training_x
        -- input x has more observations than it does features.
        -- lambda_param has a value greater than 0
    """
    

In [218]:
                    ### TESTING 
        output_y = np.array([208500, 181500, 223500, 
                                140000, 250000, 143000, 
                                307000, 200000, 129900, 
                                118000])
        aug_x = np. array([[   1., 1710., 2003.],
                           [   1., 1262., 1976.],
                           [   1., 1786., 2001.],
                           [   1., 1717., 1915.],
                           [   1., 2198., 2000.],
                           [   1., 1362., 1993.],
                           [   1., 1694., 2004.],
                           [   1., 2090., 1973.],
                           [   1., 1774., 1931.],
                           [   1., 1077., 1939.]])
        
        wts = np.array([-2.29223802e+06, 5.92536529e+01, 1.20780450e+03])
        n = aug_x.shape[0]
        d = aug_x.shape[1]
        # empty list 
        sqdiflist = []
        # Xi*weights
        xiweights = -1*aug_x@wts
        # output_y - Xi*weights
        # output_y[0] = 208500 + xiweights[0]= -228318.139959 = -19818.13995899976
        diff = np.add(output_y,xiweights)
        sqdiff = np.square(diff)
        for x in sqdiff:
            sqdiflist.append(x)
        squares_summed = sum(sqdiflist)
        squares_summed
        noise = (1/(n-d))*squares_summed
        noise
                

1471223687.1592972

#### Question 7: Posterier Covariance  

$$\Sigma = (\lambda \ I + \sigma^{- 2}\ X^T\ X)^{−1}$$

In [247]:
### GRADED
### Code a function called "calc_post_cov_mtx"
### ACCEPT three inputs:
### One numpy array for the augmented x-matrix
### Two floats for sigma-squared and a lambda_param

### Calculate the covariance matrix of the posterior (capital sigma), via equation given above.
### RETURN that matrix.

### YOUR ANSWER BELOW


def calc_post_cov_mtx(aug_x, sigma_squared, lambda_param):
    # Create identity matrix with lambda coef applied 
    first_var = lambda_param*np.identity(len(aug_x[0]))
        
    # sigma^-2 * Xmatrix.transpose * Xmatrix 
    sec_var = (1/sigma_squared)*aug_x.T@aug_x
        
    final = np.add(first_var,sec_var)
    big_sigma = np.linalg.inv(final)
    return big_sigma
    
    
    """
    Calculate the covariance of the posterior for Bayesian parameters
    
    Positional arguments:
        aug_x -- matrix of training input data; preprocessed
        sigma_squared -- estimation of sigma^2
        lambda_param -- lambda parameter that controls how heavily
        to penalize large weight values
        
    Example:
        output_y = np.array([208500, 181500, 223500, 
                                140000, 250000, 143000, 
                                307000, 200000, 129900, 
                                118000])
        aug_x = np. array([[   1., 1710., 2003.],
                           [   1., 1262., 1976.],
                           [   1., 1786., 2001.],
                           [   1., 1717., 1915.],
                           [   1., 2198., 2000.],
                           [   1., 1362., 1993.],
                           [   1., 1694., 2004.],
                           [   1., 2090., 1973.],
                           [   1., 1774., 1931.],
                           [   1., 1077., 1939.]])
        lambda_param = 0.01
        
        ml_weights = calculate_map_coefficients(aug_x, output_y,0,0)
        
        sigma_squared = estimate_data_noise(aug_x, output_y, ml_weights)
        
        print(calc_post_cov_mtx(aug_x, sigma_squared, lambda_param))
        # --> [[ 9.99999874e+01 -1.95016334e-02 -2.48082095e-02]
               [-1.95016334e-02  6.28700339e+01 -3.85675510e+01]
               [-2.48082095e-02 -3.85675510e+01  5.10719826e+01]]

    Assumptions:
        -- training_input_y is a vector whose length is the same as the
        number of rows in training_x
        -- lambda_param has a value greater than 0
    
    """
    

In [246]:
        ### TESTING 
        output_y = np.array([208500, 181500, 223500, 
                                140000, 250000, 143000, 
                                307000, 200000, 129900, 
                                118000])
        aug_x = np. array([[   1., 1710., 2003.],
                           [   1., 1262., 1976.],
                           [   1., 1786., 2001.],
                           [   1., 1717., 1915.],
                           [   1., 2198., 2000.],
                           [   1., 1362., 1993.],
                           [   1., 1694., 2004.],
                           [   1., 2090., 1973.],
                           [   1., 1774., 1931.],
                           [   1., 1077., 1939.]])
        lambda_param = 0.01
        # GIVENS 
        ml_weights = calculate_map_coefficients(aug_x, output_y,0,0)
        sigma_squared = estimate_data_noise(aug_x, output_y, ml_weights)
        
        # Create identity matrix with lambda coef applied 
        first_var = lambda_param*np.identity(len(aug_x[0]))
        
        # sigma^-2 * Xmatrix.transpose * Xmatrix 
        sec_var = (1/sigma_squared)*aug_x.T@aug_x
        
        final = np.add(first_var,sec_var)
        big_sigma = np.linalg.inv(final)
        big_sigma
        
        
      

array([[ 9.99999874e+01, -1.95016334e-02, -2.48082095e-02],
       [-1.95016334e-02,  6.28700339e+01, -3.85675510e+01],
       [-2.48082095e-02, -3.85675510e+01,  5.10719826e+01]])

Now we have functions for
$$\Sigma = (\lambda \ I + \sigma^{- 2}\ X^T\ X)^{−1}$$
$$\mu = w_{map}=(\lambda\ \sigma^2 I+X^TX)^{-1}X^Ty$$

And thus, $p(w|y, X) = N(w|\mu, \Sigma)$, the posterior distribution of the linear regression parameters may be described.

When we want to predict an unknown value, $y_0$ given observations $x_0$:  
$p( y_0|x_0,y,X) = N(y_0|\mu_0,\sigma^2_0)$  
$\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \mu_0 = x^T_0\mu$  
$\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \sigma^2_0 = \sigma^2 + x_0^T\Sigma x_0$  

#### Question 8

In [ ]:
### GRADED
### Code a function called "predict"
### ACCEPT four inputs, three numpy arrays, and one number:
### A 1-dimensional array corresponding to an augmented_x vector.
### A vector corresponding to the MAP weights, or "mu"
### A square matrix for the "big_sigma" term
### A positive number for the "sigma_squared" term

### Using the above equations

### RETURN mu_0 and sigma_squared_0 - a point estimate and variance
### for the prediction for x.

### YOUR ANSWER BELOW

def predict( aug_x, weights, big_sig, sigma_squared):
    """
    Calculate point estimates and uncertainty for new values of x
    
    Positional Arguments:
        aug_x -- augmented matrix of observations for predictions
        weights -- MAP weights calculated from Bayesian LR
        big_sig -- The posterior covarience matrix, from Bayesian LR
        sigma_squared -- The observed uncertainty in Bayesian LR
        
    Example:
        output_y = np.array([208500, 181500, 223500, 
                                140000, 250000, 143000, 
                                307000, 200000, 129900, 
                                118000])
                                
        aug_x = np. array([[   1., 1710., 2003.],
                           [   1., 1262., 1976.],
                           [   1., 1786., 2001.],
                           [   1., 1717., 1915.],
                           [   1., 2198., 2000.],
                           [   1., 1362., 1993.],
                           [   1., 1694., 2004.],
                           [   1., 2090., 1973.],
                           [   1., 1774., 1931.],
                           [   1., 1077., 1939.]])
        lambda_param = 0.01
        
        ml_weights = calculate_map_coefficients(aug_x, output_y,0,0)
        
        sigma_squared = estimate_data_noise(aug_x, output_y, ml_weights)
        
        map_weights = calculate_map_coefficients(aug_x, output_y, lambda_param, sigma_squared)
        
        big_sig = calc_post_cov_mtx(aug_x, sigma_squared, lambda_param)
        
        to_pred2 = np.array([1,1700,1980])
        
        print(predict(to_pred2, map_weights, big_sig, sigma_squared))
        #-->(158741.6306608729, 1593503867.9060116)
        
    """
    mu_0 = float()
    sigma_squared_0 = float()
    
    return mu_0, sigma_squared_0

In [ ]:
#
# AUTOGRADER TEST - DO NOT REMOVE
#


<a id = "data"></a>
### Data Refresher  

Once again, we will be using the Bayesian regression functions on house price data. Observations from this data will be used to test the functions you have created.

In [ ]:
### Read in the data
tr_path = '../resource/asnlib/publicdata/train.csv'
data = pd.read_csv(tr_path)  

### The .head() function shows the first few lines of data for perspecitve
data.head()

In [ ]:
data.plot('GrLivArea', 'SalePrice', kind = 'scatter', marker = 'x');

In [ ]:
data.plot('YearBuilt', 'SalePrice', kind = 'scatter', marker = 'x');

#### Question 9: On Housing Data

Use your functions above to return a $\Sigma$ and $\mu$ for our housing dataset.

Use "SalePrice" as the target, and "GrLivArea" and "YearBuilt" as predictors. Keep "GrLivArea" and "YearBuild", in that order. (Order is important for grading.)  

**USE ALL OBSERVATIONS IN `data` NOT JUST THE FIRST 100 AS IS DONE IN THE EXAMPLE**

e.g.
```
input_x = data[['GrLivArea, 'YearBuilt']].values
```

Use .1 for $\lambda$ 

Below, return the $\mu$ vector to the variable "mu"  

Return the $\Sigma$ matrix to the variable "big_sig"

Remember, the `fit_bayes_reg` function should work if you defined the above equations correctly.

In [ ]:
### GRADED
### Follow directions above
### YOUR ANSWER BELOW

"""
Example:
    input_x = data[['GrLivArea','YearBuilt']].head(100).values
    output_y = data['SalePrice'].head(100).values
    lambda_param = .1
    
    < --- CODE BLOCK --->
    
    print(mu)
    #--> np.array([2.10423243e-02, 4.10449281e+01, 4.22635006e+01])
    print(big_sig)
    #--> 
    np.array([[ 9.99999861e+00, -1.75179751e-03, -2.74204060e-03],
              [-1.75179751e-03,  6.50420674e+00, -3.47271893e+00],
              [-2.74204060e-03, -3.47271893e+00,  4.60297584e+00]])
"""

mu = np.array([])
big_sig = np.array([[]])

In [ ]:
#
# AUTOGRADER TEST - DO NOT REMOVE
#


Remeber to check out the other notebook for a demonstration of `pymc3`